- name: variable from play level
  hosts: localhost
  Vars:
  Cource: "DevOps"
  Trainer: "sivakumar"
  Duration: "120HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Cource}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
