- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  
  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enable
    ansible.builtin.service:
       name: mongodb
       state: started
       enabled: yes 

  - name: allow remote conections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1 
      replace: 0.0.0.0

  - name: start and enable
    ansible.builtin.service:
       name: mongodb
       state: restarted
       enabled: yes  

                

